import Head from 'next/head';
import NavigationBar from '../layout/NavigationBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Dribble Clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main >
       <NavigationBar/>
      </main>
    </>
  )
}
