import Head from "next/head";
import NavigationBar from "@dribble/layout/NavigationBar";
import Hero from "@dribble/layout/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dribble Clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <NavigationBar />
        <Hero />
      </header>

      <main></main>
    </>
  );
}
